[package]
name = "hyprland-autoname-workspaces-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
hyprland =  { git = "https://github.com/cyrinux/hyprland-rs.git" }
lazy_static = "1.4.0"
