[package]
name = "hyprland-autoname-workspaces"
authors = ["Cyril Levis", "Maxim Baz"]
version = "0.3.0"
edition = "2021"
categories = ["gui"]
keywords = ["linux", "desktop-application", "hyprland","waybar","wayland"]
description = "This app automatically rename workspaces with icons of started applications."
readme = "README.md"
license = "ISC"
homepage = "https://github.com/cyrinux/hyprland-autoname-workspaces"
repository = "https://github.com/cyrinux/hyprland-autoname-workspaces"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
hyprland = { git = "https://github.com/cyrinux/hyprland-rs", branch = "fix/read-all-socket-data" }
signal-hook = "0.3.14"
toml = { version = "0.5.10", features = ["indexmap", "preserve_order"] }
xdg = "2.4.1"
inotify = "0.10.0"
rustc-hash = "1.1.0"
serde = "1.0.152"
